/*
 * Copyright 2017-2020 Alex Magalhaes <alex@pensatocode.org>
 * Copyright 2012-2014 Tomasz Nurkiewicz <nurkiewicz@gmail.com>.
 * Copyright 2016 Jakub Jirutka <jakub@jirutka.cz>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pensatocode.simplicity.jdbc.sql;

import org.pensatocode.simplicity.jdbc.TableDescription;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;

public interface SqlGenerator {

    /**
     * This method is used by {@link SqlGeneratorFactory} to select a right SQL Generator.
     *
     * @param metadata The database metadata.
     * @return Whether is this generator compatible with the database described by the given {@code metadata}.
     */
    boolean isCompatible(DatabaseMetaData metadata) throws SQLException;

    String count(TableDescription table);

    String deleteAll(TableDescription table);

    String deleteByPK(TableDescription table);

    String existsByPK(TableDescription table);

    String insert(TableDescription table, Boolean autoGeneratedKey);

    String selectAll(TableDescription table);

    String selectAll(TableDescription table, String whereClause);

    String selectAll(TableDescription table, Pageable page);

    String selectAll(TableDescription table, String whereClause, Pageable page);

    String selectAll(TableDescription table, Sort sort);

    String selectAll(TableDescription table, String whereClause, Sort sort);

    String selectByPK(TableDescription table);

    String update(TableDescription table);
}
